include("unit_tests_obtain_name.jl")
include("unit_tests_obtain_segments.jl")
include("unit_tests_obtain_segment_count.jl")
include("unit_tests_obtain_residue_count.jl")
include("unit_tests_obtain_atom_count.jl")
include("unit_tests_obtain_identifier.jl")
