test_obtain_Atom(Atom(atom_name=" A"), :atom_name, "A")
test_obtain_Atom(Atom(atom_name=" A"), :raw_atom_name, " A")
test_obtain_Atom(Atom(alt_location='1'), :alt_location, '1')
test_obtain_Atom(Atom(insertion='I'), :insertion, 'I')
test_obtain_Atom(Atom(occupancy=0.99), :occupancy, 0.99)
test_obtain_Atom(Atom(beta=0.99), :beta, 0.99)
test_obtain_Atom(Atom(element="E"), :element, "E")
test_obtain_Atom(Atom(charge=1), :charge, 1)
test_obtain_Atom(Atom(index=99), :index, 99)
test_obtain_Atom(Atom(residue_name="ALA"), :residue_name, "ALA")
test_obtain_Atom(Atom(residue_id=11), :residue_id, 11)
test_obtain_Atom(Atom(segment_name="SEG"), :segment_name, "SEG")
test_obtain_Atom(Atom(chain_name="C"), :chain_name, "C")
test_obtain_Atom(Atom(system_name="S"), :system_name, "S")
test_obtain_Atom(Atom(coordinate=[1., 0., 0.]), :coordinate, Array[[1., 0., 0.]])
test_obtain_Atom(Atom(atom_name="A"), :topology, TopologicAtom(atom_name="A"))