test_obtain_TopologicMolecularSystem(
    make_topologic_molecular_system(chains=[
        make_topologic_chain(segments=[
            make_topologic_segment(),
            make_topologic_segment()
        ]),
        make_topologic_chain(),
    ]), 
    :member_count_tree, 
    member_count_tree(
        make_topologic_molecular_system(chains=[
            make_topologic_chain(segments=[
                make_topologic_segment(),
                make_topologic_segment()
            ]),
            make_topologic_chain(),
        ]),
        4
    ),
    "test 1",
    4
)