include(joinpath("assort", "all.jl"))
include(joinpath("catalog", "all.jl"))
include(joinpath("coordinate", "all.jl"))
include(joinpath("hierarchy", "all.jl"))
include(joinpath("identifier", "all.jl"))
include(joinpath("move", "all.jl"))
include(joinpath("mutate", "all.jl"))
include(joinpath("synthesize", "all.jl"))
include(joinpath("extract", "all.jl"))
include(joinpath("make","all.jl"))